// This file is part of security-keys-rust. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/security-keys-rust/master/COPYRIGHT. No part of security-keys-rust, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
// Copyright © 2021 The developers of security-keys-rust. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/security-keys-rust/master/COPYRIGHT.


use crate::u3;
use super::class_and_protocol::ClassAndProtocol;
use super::class_and_protocol::DeviceOrAlternateSetting;
use crate::control_transfers::ControlTransferError;
use super::configuration::Configuration;
use super::configuration::ConfigurationNumber;
use super::configuration::ConfigurationParseError;
use super::configuration::GetConfigurationDescriptorBackendError;
use super::configuration::get_active_config_descriptor;
use super::configuration::get_config_descriptor;
use super::libusb::device::get_device_descriptor;
use super::libusb::device::get_bus_number;
use super::libusb::device::get_device_address;
use super::libusb::device::get_device_speed;
use super::libusb::device::get_port_number;
use super::libusb::device::get_port_numbers;
use super::string::LocalizedStrings;
use super::string::StringFinder;
use super::string::language::Language;
use super::version::Version;
use super::version::VersionParseError;
use arrayvec::ArrayVec;
use indexmap::map::IndexMap;
use libusb1_sys::{libusb_config_descriptor, libusb_release_interface, libusb_close, libusb_open};
use libusb1_sys::libusb_device;
use libusb1_sys::libusb_device_descriptor;
use libusb1_sys::libusb_device_handle;
use libusb1_sys::libusb_get_active_config_descriptor;
use libusb1_sys::libusb_get_bus_number;
use libusb1_sys::libusb_get_config_descriptor;
use libusb1_sys::libusb_get_configuration;
use libusb1_sys::libusb_get_device;
use libusb1_sys::libusb_get_device_address;
use libusb1_sys::libusb_get_device_descriptor;
use libusb1_sys::libusb_get_device_speed;
use libusb1_sys::libusb_get_parent;
use libusb1_sys::libusb_get_port_number;
use libusb1_sys::libusb_get_port_numbers;
use libusb1_sys::constants::LIBUSB_ERROR_IO;
use libusb1_sys::constants::LIBUSB_ERROR_INVALID_PARAM;
use libusb1_sys::constants::LIBUSB_ERROR_ACCESS;
use libusb1_sys::constants::LIBUSB_ERROR_NO_DEVICE;
use libusb1_sys::constants::LIBUSB_ERROR_BUSY;
use libusb1_sys::constants::LIBUSB_ERROR_TIMEOUT;
use libusb1_sys::constants::LIBUSB_ERROR_NOT_FOUND;
use libusb1_sys::constants::LIBUSB_ERROR_OVERFLOW;
use libusb1_sys::constants::LIBUSB_ERROR_PIPE;
use libusb1_sys::constants::LIBUSB_ERROR_INTERRUPTED;
use libusb1_sys::constants::LIBUSB_ERROR_NO_MEM;
use libusb1_sys::constants::LIBUSB_ERROR_NOT_SUPPORTED;
use libusb1_sys::constants::LIBUSB_ERROR_OTHER;
use libusb1_sys::constants::LIBUSB_SPEED_FULL;
use libusb1_sys::constants::LIBUSB_SPEED_HIGH;
use libusb1_sys::constants::LIBUSB_SPEED_LOW;
use libusb1_sys::constants::LIBUSB_SPEED_SUPER;
use libusb1_sys::constants::LIBUSB_SPEED_UNKNOWN;
use likely::likely;
use likely::unlikely;
use std::error;
use std::fmt;
use std::fmt::Debug;
use std::fmt::Display;
use std::fmt::Formatter;
use std::mem::MaybeUninit;
use std::mem::transmute;
use std::ptr::NonNull;
use swiss_army_knife::non_zero::new_non_null;
use swiss_army_knife::get_unchecked::GetUnchecked;
use crate::interface::InterfaceNumber;


include!("DeadOrAlive.rs");
include!("Device.rs");
include!("DeviceHandle.rs");
include!("DeviceHandleOpenError.rs");
include!("DeviceParseError.rs");
include!("get_bus_number.rs");
include!("get_device.rs");
include!("get_device_address.rs");
include!("get_device_descriptor.rs");
include!("get_device_speed.rs");
include!("get_parent.rs");
include!("get_port_number.rs");
include!("get_port_numbers.rs");
include!("MaximumDevicePortNumbers.rs");
include!("PortNumber.rs");
include!("ProductIdentifier.rs");
include!("Speed.rs");
include!("LocalizedStrings");
include!("VendorIdentifier.rs");
