// This file is part of security-keys-rust. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/security-keys-rust/master/COPYRIGHT. No part of security-keys-rust, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
// Copyright © 2021 The developers of security-keys-rust. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/security-keys-rust/master/COPYRIGHT.


use self::c::constants::ATR_BUFFER_SIZE;
use self::c::constants::AttributeClassShift;
use self::c::constants::INFINITE;
use self::c::constants::MAX_BUFFER_SIZE;
use self::c::constants::MAX_BUFFER_SIZE_EXTENDED;
use self::c::constants::MAX_READERNAME;
use self::c::constants::PCSCLITE_MAX_READERS_CONTEXTS;
use self::c::constants::SCARD_ABSENT;
use self::c::constants::SCARD_ATTR_ASYNC_PROTOCOL_TYPES;
use self::c::constants::SCARD_ATTR_ATR_STRING;
use self::c::constants::SCARD_ATTR_CHANNEL_ID;
use self::c::constants::SCARD_ATTR_CHARACTERISTICS;
use self::c::constants::SCARD_ATTR_CURRENT_BWT;
use self::c::constants::SCARD_ATTR_CURRENT_CLK;
use self::c::constants::SCARD_ATTR_CURRENT_CWT;
use self::c::constants::SCARD_ATTR_CURRENT_D;
use self::c::constants::SCARD_ATTR_CURRENT_EBC_ENCODING;
use self::c::constants::SCARD_ATTR_CURRENT_F;
use self::c::constants::SCARD_ATTR_CURRENT_IFSC;
use self::c::constants::SCARD_ATTR_CURRENT_IFSD;
use self::c::constants::SCARD_ATTR_CURRENT_IO_STATE;
use self::c::constants::SCARD_ATTR_CURRENT_N;
use self::c::constants::SCARD_ATTR_CURRENT_PROTOCOL_TYPE;
use self::c::constants::SCARD_ATTR_CURRENT_W;
use self::c::constants::SCARD_ATTR_DEFAULT_CLK;
use self::c::constants::SCARD_ATTR_DEFAULT_DATA_RATE;
use self::c::constants::SCARD_ATTR_DEVICE_FRIENDLY_NAME;
use self::c::constants::SCARD_ATTR_DEVICE_IN_USE;
use self::c::constants::SCARD_ATTR_DEVICE_SYSTEM_NAME;
use self::c::constants::SCARD_ATTR_DEVICE_UNIT;
use self::c::constants::SCARD_ATTR_ESC_AUTHREQUEST;
use self::c::constants::SCARD_ATTR_ESC_CANCEL;
use self::c::constants::SCARD_ATTR_ESC_RESET;
use self::c::constants::SCARD_ATTR_EXTENDED_BWT;
use self::c::constants::SCARD_ATTR_ICC_INTERFACE_STATUS;
use self::c::constants::SCARD_ATTR_ICC_PRESENCE;
use self::c::constants::SCARD_ATTR_ICC_TYPE_PER_ATR;
use self::c::constants::SCARD_ATTR_MAXINPUT;
use self::c::constants::SCARD_ATTR_MAX_CLK;
use self::c::constants::SCARD_ATTR_MAX_DATA_RATE;
use self::c::constants::SCARD_ATTR_MAX_IFSD;
use self::c::constants::SCARD_ATTR_POWER_MGMT_SUPPORT;
use self::c::constants::SCARD_ATTR_SUPRESS_T1_IFS_REQUEST;
use self::c::constants::SCARD_ATTR_SYNC_PROTOCOL_TYPES;
use self::c::constants::SCARD_ATTR_USER_AUTH_INPUT_DEVICE;
use self::c::constants::SCARD_ATTR_USER_TO_CARD_AUTH_DEVICE;
use self::c::constants::SCARD_ATTR_VENDOR_IFD_SERIAL_NO;
use self::c::constants::SCARD_ATTR_VENDOR_IFD_TYPE;
use self::c::constants::SCARD_ATTR_VENDOR_IFD_VERSION;
use self::c::constants::SCARD_ATTR_VENDOR_NAME;
use self::c::constants::SCARD_CLASS_COMMUNICATIONS;
use self::c::constants::SCARD_CLASS_ICC_STATE;
use self::c::constants::SCARD_CLASS_IFD_PROTOCOL;
use self::c::constants::SCARD_CLASS_MECHANICAL;
use self::c::constants::SCARD_CLASS_POWER_MGMT;
use self::c::constants::SCARD_CLASS_PROTOCOL;
use self::c::constants::SCARD_CLASS_SECURITY;
use self::c::constants::SCARD_CLASS_SYSTEM;
use self::c::constants::SCARD_CLASS_VENDOR_DEFINED;
use self::c::constants::SCARD_CLASS_VENDOR_INFO;
use self::c::constants::SCARD_EJECT_CARD;
use self::c::constants::SCARD_E_CANCELLED;
use self::c::constants::SCARD_E_INSUFFICIENT_BUFFER;
use self::c::constants::SCARD_E_INVALID_HANDLE;
use self::c::constants::SCARD_E_INVALID_PARAMETER;
use self::c::constants::SCARD_E_INVALID_VALUE;
use self::c::constants::SCARD_E_NO_MEMORY;
use self::c::constants::SCARD_E_NO_READERS_AVAILABLE;
use self::c::constants::SCARD_E_NO_SERVICE;
use self::c::constants::SCARD_E_NO_SMARTCARD;
use self::c::constants::SCARD_E_NOT_TRANSACTED;
use self::c::constants::SCARD_E_PROTO_MISMATCH;
use self::c::constants::SCARD_E_READER_UNAVAILABLE;
use self::c::constants::SCARD_E_SHARING_VIOLATION;
use self::c::constants::SCARD_E_TIMEOUT;
use self::c::constants::SCARD_E_UNKNOWN_READER;
use self::c::constants::SCARD_E_UNSUPPORTED_FEATURE;
use self::c::constants::SCARD_F_COMM_ERROR;
use self::c::constants::SCARD_F_INTERNAL_ERROR;
use self::c::constants::SCARD_LEAVE_CARD;
use self::c::constants::SCARD_NEGOTIABLE;
use self::c::constants::SCARD_POWERED;
use self::c::constants::SCARD_PRESENT;
use self::c::constants::SCARD_PROTOCOL_RAW;
use self::c::constants::SCARD_PROTOCOL_T0;
use self::c::constants::SCARD_PROTOCOL_T15;
use self::c::constants::SCARD_PROTOCOL_T1;
use self::c::constants::SCARD_RESET_CARD;
use self::c::constants::SCARD_SCOPE_SYSTEM;
use self::c::constants::SCARD_SHARE_DIRECT;
use self::c::constants::SCARD_SHARE_EXCLUSIVE;
use self::c::constants::SCARD_SHARE_SHARED;
use self::c::constants::SCARD_SPECIFIC;
use self::c::constants::SCARD_STATE_CHANGED;
use self::c::constants::SCARD_STATE_EMPTY;
use self::c::constants::SCARD_STATE_EXCLUSIVE;
use self::c::constants::SCARD_STATE_IGNORE;
use self::c::constants::SCARD_STATE_INUSE;
use self::c::constants::SCARD_STATE_MUTE;
use self::c::constants::SCARD_STATE_PRESENT;
use self::c::constants::SCARD_STATE_UNAVAILABLE;
use self::c::constants::SCARD_STATE_UNAWARE;
use self::c::constants::SCARD_STATE_UNKNOWN;
use self::c::constants::SCARD_SWALLOWED;
use self::c::constants::SCARD_S_SUCCESS;
use self::c::constants::SCARD_UNKNOWN;
use self::c::constants::SCARD_UNPOWER_CARD;
use self::c::constants::SCARD_W_REMOVED_CARD;
use self::c::constants::SCARD_W_RESET_CARD;
use self::c::constants::SCARD_W_UNPOWERED_CARD;
use self::c::constants::SCARD_W_UNRESPONSIVE_CARD;
use self::c::functions::SCARD_CTL_CODE;
use self::c::functions::SCardBeginTransaction;
use self::c::functions::SCardCancel;
use self::c::functions::SCardConnect;
use self::c::functions::SCardControl;
use self::c::functions::SCardDisconnect;
use self::c::functions::SCardEndTransaction;
use self::c::functions::SCardEstablishContext;
use self::c::functions::SCardGetAttrib;
use self::c::functions::SCardGetStatusChange;
use self::c::functions::SCardIsValidContext;
use self::c::functions::SCardListReaders;
use self::c::functions::SCardReconnect;
use self::c::functions::SCardReleaseContext;
use self::c::functions::SCardSetAttrib;
use self::c::functions::SCardStatus;
use self::c::functions::SCardTransmit;
use self::c::fundamental_types::DWORD;
use self::c::statics::g_rgSCardRawPci;
use self::c::statics::g_rgSCardT0Pci;
use self::c::statics::g_rgSCardT1Pci;
use self::c::types::SCARDCONTEXT;
use self::c::types::SCARDHANDLE;
use self::c::types::SCARD_IO_REQUEST;
use self::c::types::SCARD_READERSTATE;
use self::errors::ActivityError;
use self::errors::CardCommandError;
use self::errors::ConnectCardError;
use self::errors::CardReaderNameError;
use self::errors::CardReaderStatusChangeError;
use self::errors::CardStatusError;
use self::errors::CardTransmissionError;
use self::errors::CommunicationError;
use self::errors::ReconnectionUnavailableOrCommunicationError;
use self::errors::TransactionError;
use self::errors::UnavailableOrCommunicationError;
use self::errors::UnavailableError;
use self::errors::WithDisconnectError;
use arrayvec::ArrayVec;
use libc::c_char;
use libc::c_void;
use likely::likely;
use likely::unlikely;
use memchr::memchr;
use std::borrow::{Cow, Borrow};
use std::cell::Cell;
use std::cmp::max;
use std::collections::HashSet;
use std::convert::TryFrom;
use std::error;
use std::ffi::CStr;
use std::ffi::CString;
use std::marker::PhantomData;
use std::mem::transmute;
use std::mem::MaybeUninit;
use std::num::NonZeroU32;
use std::ops::Deref;
use std::ptr::null;
use std::ptr::null_mut;
use std::ptr::read;
use std::rc::Rc;
use std::thread::sleep;
use std::time::Duration;
use swiss_army_knife::get_unchecked::GetUnchecked;
use swiss_army_knife::unsafe_initialization::unsafe_uninitialized;
use strum::IntoEnumIterator;
use strum_macros::EnumIter;


mod c;

pub(crate) mod errors;


include!("AnswerToReset.rs");
include!("AttributeClass.rs");
include!("AttributeIdentifier.rs");
include!("CardDisposition.rs");
include!("CardReaderEventName.rs");
include!("CardReaderName.rs");
include!("CardReaderNames.rs");
include!("CardReaderNamesBuffer.rs");
include!("CardReaderNamesBufferMaximumSize.rs");
include!("CardReaderNamesIterator.rs");
include!("CardReaderState.rs");
include!("CardReaderStates.rs");
include!("CardSharedAccessBackOff.rs");
include!("CardStatus.rs");
include!("ChangeCardReaderStateNotification.rs");
include!("ConnectedCard.rs");
include!("ConnectedCardOrTransaction.rs");
include!("ConnectedCardTransaction.rs");
include!("Context.rs");
include!("ContextInner.rs");
include!("ControlCode.rs");
include!("InsertionsAndRemovalsCount.rs");
include!("PresentExclusivity.rs");
include!("PreferredProtocols.rs");
include!("Protocol.rs");
include!("RemainingResetRetryAttempts.rs");
include!("Scope.rs");
include!("ShareModeAndPreferredProtocols.rs");
include!("StateChanged.rs");
include!("Timeout.rs");
